name: obs_tracker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  obs_websocket: ^5.2.3
  flutter_drawing_board: ^0.9.8
  chewie: ^1.11.3
  video_player: ^2.10.0
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  uuid: ^4.5.2
  auto_route: ^7.5.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.1.1
  photo_view: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/config/app_config.json